name: minim
channels:
  - conda-forge
  - microsoft
dependencies:
  # CORE DEPENDENCIES
  - levenshtein
  - mutagen
  - numpy
  - pycryptodome
  - requests
  # OPTIONAL DEPENDENCIES
  - ffmpeg
  - flask
  - pytest-playwright
  # DEVELOPMENT DEPENDENCIES
  - pytest
  - ruff
  # DOCUMENTATION DEPENDENCIES
  - furo
  - ipywidgets
  - jupyterlab
  - myst-nb
  - numpydoc
  - sphinx
  - sphinx-copybutton
  - sphinx-togglebutton