name: Continuous Integration
on: [push]
env:
  SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
  SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
  SPOTIFY_SP_DC: ${{ secrets.SPOTIFY_SP_DC }}
  TIDAL_CLIENT_ID: ${{ secrets.TIDAL_CLIENT_ID }}
  TIDAL_CLIENT_SECRET: ${{ secrets.TIDAL_CLIENT_SECRET }}
  TIDAL_PRIVATE_CLIENT_ID: ${{ secrets.TIDAL_PRIVATE_CLIENT_ID }}
  TIDAL_PRIVATE_CLIENT_SECRET: ${{ secrets.TIDAL_PRIVATE_CLIENT_SECRET }}
jobs:
  build:
    name: continuous-integration-${{matrix.python-version}}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    timeout-minutes: 60
    steps:      
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: conda-forge
          python-version: ${{ matrix.python-version }}
      - uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg
      - name: install-dependencies
        run: |
          python3 -m pip install -r requirements_minimal.txt
      - name: lint-ruff
        run: |
          python3 -m pip install ruff
          ruff --target-version=py39 .
        continue-on-error: true
      - name: test-coverage-pytest
        run: |
          python3 -m pip install coverage pytest
          coverage run -m pytest
      - name: upload-codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}